	const items = [
	{day: 3,
	heading:"Den třetí",
	content:"Příprava" },
	{day: 24, 
	heading: "Den dvacátý",
	content: "Příprava"},
	{day: 1, 
	heading: "Den první",
	content: "Příprava"},
	{day: 18, 
	heading:"Den osmnáctý",
	content: "Příprava"},
	{day:5, 
	heading:"Den pátý",
	content: "Příprava"},
	{day: 10,
	heading: "Den desátý",
	content: "Příprava"},
	{day: 23, 
	heading:"Den dvacátýtřetí",
	content: "Příprava"},
	{day: 12, 
	heading:"Den dvanáctý",
	content:"Příprava"},
	{day: 15, 
	heading:"Den patnáctý",
	content:"Příprava"},
	{day: 20, 
	heading:"Den dvacátý",
	content:"Příprava" },
	{day: 14, 
	heading:"Den čtrnáctý",
	content:"Příprava"},
	{day: 7, 
	heading:"Den sedmý",
	content:"Příprava"},
	{day: 6, 
	heading:"Den šestý",
	content:"Příprava"},
	{day: 16, 
	heading:"Den šestnáctý",
	content:"Příprava" },
	{day: 8,
	heading:"Den osmý", 
	content:"Příprava" },
	{day: 6, 
	heading:"Den šestý",
	content:"Příprava" },
	{day: 11,
	heading:"Den jedenáctý",
	content:"Příprava" },
	{day: 21, 
	heading:"Den dvacátýprvní",
	content:"Příprava"},
	{day: 2, 
	heading:"Den druhý",
	content:"Příprava" },
	{day: 4,
	heading:"Den čtvrtý",
	content:"Příprava"},
	{day:9,
	heading:"Den devátý",
	content: "Příprava"},
	{day: 19,
	heading:"Den devatenáctý",
	content:"Příprava"},
	{day:13,
	heading:"Den třináctý",
	content:"Příprava" },
	{day:17, 
	heading:"Den sedmnáctý",
	content:"Příprava"},
	{day:22,
	heading:"Den dvacátýdruhý",
	content:"Příprava" }
	]

	export default items;